# -*- coding: utf-8 -*-
"""SDT_TaskNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uLCPojcC8Zr0ceF2hXWBfyGJsrm3frFN
"""

import numpy as np
weights = np.array([[0.5,0.33,-0.5],[0.5,0.33,-0.5],[-0.5,0.33,0.5],[-0.5,0.33,0.5],[0.5,0.34,0.5],
[0.5,0.33,-0.5],[-0.5,0.33,0.5],[1,1,1]])
print(weights)

"""[0.5,0.5,-0.5],[0.5,0.5,-0.5],[-0.5,0.5,0.5],[-0.5,0.5,0.5],[0.5,0.5,0.5],
[0.5,0.5,-0.5],[-0.5,0.5,0.5],[0,0,0]
"""

ip = [1,1,1,1,1,0,0,1]
print("Enter input vector")
#for i in range(8):
 # a = int(input())
  #ip.append(a)
op = np.matmul(ip,weights)
message = ["Steer Right","Do not Steer","Steer Left"]
print(op)
flag = 0
for i in range(len(op)):
  if op[i] >=1 and op[i]==max(op):
    print(message[i])
    flag += 1
    break
if flag == 0:
  print(message[0])

"""0,0,0,0,1,1,0,1"""